# Use Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose port 6000 for Flask in consumer.py
EXPOSE 6000

# Run the consumer application
CMD ["python", "consumer.py"]

