apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
        ports:
          - containerPort: {{ .Values.consumer.containerPort }}
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "{{ .Values.consumer.kafka.bootstrapServer }}"
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_URI
            value: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017"
