apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
        env:
          - name: KAFKA_NODE_ID
            value: "{{ .Values.kafka.config.KAFKA_NODE_ID }}"
          - name: KAFKA_PROCESS_ROLES
            value: "{{ .Values.kafka.config.KAFKA_PROCESS_ROLES }}"
          - name: KAFKA_LISTENERS
            value: "{{ .Values.kafka.config.KAFKA_LISTENERS }}"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "{{ .Values.kafka.config.KAFKA_ADVERTISED_LISTENERS }}"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "{{ .Values.kafka.config.KAFKA_CONTROLLER_LISTENER_NAMES }}"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "{{ .Values.kafka.config.KAFKA_LISTENER_SECURITY_PROTOCOL_MAP }}"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "{{ .Values.kafka.config.KAFKA_CONTROLLER_QUORUM_VOTERS }}"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "{{ .Values.kafka.config.KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR }}"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "{{ .Values.kafka.config.KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR }}"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "{{ .Values.kafka.config.KAFKA_TRANSACTION_STATE_LOG_MIN_ISR }}"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "{{ .Values.kafka.config.KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS }}"
          - name: KAFKA_NUM_PARTITIONS
            value: "{{ .Values.kafka.config.KAFKA_NUM_PARTITIONS }}"
        ports:
          - containerPort: {{ .Values.kafka.service.port }}

