apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: MONGO_INITDB_ROOT_PASSWORD
        ports:
          - containerPort: {{ .Values.mongo.service.port }}
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db  # Default MongoDB data directory
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc  

